# Generated by Django 4.0.3 on 2022-05-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_charges_ch_id_alter_medicalspecialistes_sid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('department', models.CharField(choices=[('Gynacology', 'Gynacology'), ('Dermatologist', 'Dermatologist'), ('Orthology', 'Orthology'), ('Anesthesiology', 'Anesthesiology'), ('Ayurvedic', 'Ayurvedic')], max_length=200, null=True)),
            ],
        ),
    ]
