# Generated by Django 4.0.3 on 2022-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
