# Generated by Django 4.0.3 on 2022-07-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_book_date_alter_book_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=b'I01\n', serialize=False)),
                ('code', models.IntegerField()),
                ('discription', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
