# Generated by Django 4.0.3 on 2022-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='preparations',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='discription',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
